services:
    app:
        image: ghcr.io/daudnaw/dv1677-ht26-grupp4-backend:latest
        container_name: dv1677-ht26-grupp4-backend
        ports:
            - '3000:3000'
        environment:
            PORT: 3000
            MONGODB_URI: ${MONGODB_URI}
            DATABASE_NAME: ${DATABASE_NAME}
            COLLECTION_NAME: ${COLLECTION_NAME}
        restart: unless-stopped
